project_name: kernel-bindings-tests

builds:
  - id: runner
    main: ./cmd/runner
    binary: runner
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: runner-archive
    builds:
      - runner
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  disable: true

changelog:
  disable: true

release:
  github:
    owner: stringintech
    name: kernel-bindings-tests
  draft: false
  prerelease: auto
